version: "3.8"
services:
  inbulk:
    build:
      context: ./
    image: inbulk:local
    command: bash
    volumes:
      - .:/inbulk
      - ~/.gcp/credential.json:/.gcp/credential.json
      - ~/.gcp/credential.datamart.json:/.gcp/credential.datamart.json
  inbulk-test:
    build:
      context: ./
      target: test
    image: inbulk:test
    command: pytest
    volumes:
      - .:/inbulk
